import type { UiStrings } from "@/lib/i18n";

export const en: UiStrings = {
  name: "English",
  speechLang: "en-GB",
  strings: {

    pilotTour: "Pilot tour",
    stariGrad: "Stari Grad",
    heroKicker: "Belgrade, in your ear",
    heroTitle: "The city gets better when it talks back.",
    heroBody:
      "A playful, phone-first walk through Belgrade’s old town. Choose your language, follow the stops, and press play when you’re ready to listen. It keeps working when your signal doesn’t.",
    startWalk: "Start the walk",
    seeRoute: "See the route",
    badgeTime: "75–90 minutes",
    badgeFree: "Free pilot experience",
    badgeBrowser: "Works in your browser",
    todaysRoute: "Today’s route",
    routeHeadline: "From fortress walls to bohemian tables.",
    routeNote:
      "Six places. One walk. Plenty of room for a coffee, a detour, or an excellent view.",
    expectKicker: "Built for wandering, not staring at a screen.",
    expectTitle: "A route you can actually enjoy on your first day in Belgrade.",
    expectOneTitle: "Real streets, not straight lines.",
    expectOneBody:
      "Every path on the map follows pavements and passages you can actually walk, with honest distances.",
    expectTwoTitle: "Listen your way.",
    expectTwoBody:
      "The pilot uses your browser’s own speech feature, so there are no mystery downloads or audio files.",
    expectThreeTitle: "Made for the street.",
    expectThreeBody:
      "Request location when you want it, or keep moving with clear written directions.",
    footerLine: "Belgrade stories, at your pace.",

    back: "Back",
    setupKicker: "Stari Grad · pilot tour",
    setupTitle: "Set your walking mood.",
    setupBody: "A few quick choices, then the city is yours.",
    chooseLanguage: "Choose a language",
    languageNoteReady: "Narration and directions are fully translated.",
    languageNotePending:
      "This language is not written yet — the walk stays in English for now.",
    chooseTheme: "Choose a theme",
    themeHistory: "History",
    themeHistoryBody: "Fortress walls, city landmarks, and stories in between.",
    chooseLength: "How long do you have?",
    chooseDirection: "Where are you starting from?",
    openTour: "Open the pilot tour",

    counter: "Pilot",
    mapKicker: "Interactive map",
    mapTitle: "Follow the walk",
    mapHint: "Tap a numbered stop to open its story, or a faded pin to add a detour.",
    mapWholeRoute: "Whole route",
    mapThisStop: "This stop",
    mapExpand: "Expand map",
    mapCollapse: "Close map",
    mapLegendRoute: "Your route",
    mapLegendAlternative: "Alternative",
    mapLegendDetour: "Detour",
    mapLocationOn: "Your location is shown in teal.",
    mapLocationOff: "Location is optional — the whole route still works without it.",

    yourRoute: "Your route",
    routeName: "Stari Grad history walk",
    routeSummary: "{distance} · {minutes} min walking",
    routeSummaryDetours: "{distance} · {minutes} min walking · +{detour} min of detours",
    stopWord: "Stop",

    narrationReady: "Ready to listen",
    narrationPlaying: "Narration playing",
    narrationPaused: "Narration paused",
    narrationSource: "Browser speech",
    playStory: "Play story",
    resumeStory: "Resume story",
    pause: "Pause",
    stopNarration: "Stop narration",
    listenOrRead: "Listen, or read along.",
    narrationUnsupported:
      "Audio narration is not available in this browser. You can still read the story below.",
    narrationFailed:
      "Your browser could not start this narration. Try again or read the story instead.",
    narrationNoVoice:
      "Your device has no {language} voice installed, so this stop is text only. Everything written is still translated.",

    locationTitle: "Live location, if you want it",
    locationIdle: "Turn on location to see when you are close to each stop.",
    locationLoading: "Looking for your location…",
    locationDenied:
      "Location permission was denied. No problem — use the written directions below.",
    locationUnavailable:
      "Location isn’t available on this device. The route still works with directions.",
    locationArrived: "You’re at this stop — press play when you’re ready.",
    locationDistance: "{distance} from this stop. Keep following the directions.",
    useMyLocation: "Use my location",
    checkingLocation: "Checking location",

    walkNext: "Walk next",
    walkStat: "{minutes} min · {distance}",
    nextStop: "Next stop: {title}",
    finishTour: "Finish the pilot",
    tourComplete: "Tour complete",
    tourCompleteBody:
      "From here, it is an easy walk back to the centre or a gentle wander through the neighbourhood.",
    directionReverseNote:
      "The written directions were authored for the fortress-first walk. Going this way, follow the line on the map — the distance and time above are correct.",
    pathChoice: "Two ways to walk this",
    pathChosen: "Walking this way",
    detourTitle: "Worth a detour",
    detourNone: "Nothing worth stepping off the route for on this stretch.",
    detourAdd: "Add",
    detourAdded: "Added",
    detourMinutes: "+{minutes} min",
    walksKicker: "Belgrade, one walk at a time",
    walksTitle: "Choose a walk.",
    walksBody: "The Stari Grad walk is free and always will be. New neighbourhoods come with the subscription.",
    walkStops: "{count} stops",
    badgeFreeWalk: "Free",
    badgeSubscriberWalk: "Subscription",
    lockedNote: "Part of the monthly subscription. Buying is available in the Android app.",
    lockedNoteWeb: "Part of the monthly subscription, which is sold through the Android app.",
    allWalks: "All walks",
    openWalk: "Open this walk",
    offerCode: "Code",
    offerHint: "Show this screen at the counter.",
    walkEnglishOnly: "This walk is only written in English so far.",
    voiceMissing: "No voice on this device",
    voiceAvailable: "Can be read aloud",
    voiceHelpAndroid: "To hear this language, install its voice: Settings → General management → Text-to-speech → your engine → Install voice data.",
    voiceHelpIos: "To hear this language, add its voice: Settings → Accessibility → Spoken Content → Voices.",
    voiceHelpDesktop: "Your browser has no voice for this language. Phones usually do — or read along instead.",
    narrationRecorded: "Recorded voice",
    chooseWalkHere: "Five walks, one of them free",
    subscribe: "Subscribe",
    subscribePerMonth: "{price} / month",
    subscribeAllWalks: "Unlocks every walk, in every language.",
    subscribeThanks: "Thank you — every walk is unlocked.",
    subscribeFailed: "The purchase did not go through. Nothing was charged.",
    subscribeCancelled: "Purchase cancelled. Nothing was charged.",
    subscribeUnavailable: "Subscribing is only possible in the Android app for now.",
    openFreeWalk: "Open the free walk",
    language: "Language",
    theme: "Theme",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
  },
};
