import type { UiStrings } from "@/lib/i18n";

export const es: UiStrings = {
  name: "Español",
  speechLang: "es-ES",
  strings: {

    pilotTour: "Ruta piloto",
    stariGrad: "Stari Grad",
    heroKicker: "Belgrado, al oído",
    heroTitle: "La ciudad mejora cuando te responde.",
    heroBody:
      "Un paseo desenfadado por el casco viejo de Belgrado, pensado para el móvil. Elige tu idioma, sigue las paradas y dale al play cuando quieras escuchar. Sigue funcionando cuando no hay cobertura.",
    startWalk: "Empezar el paseo",
    seeRoute: "Ver la ruta",
    badgeTime: "75–90 minutos",
    badgeFree: "Experiencia piloto gratuita",
    badgeBrowser: "Funciona en tu navegador",
    todaysRoute: "La ruta de hoy",
    routeHeadline: "De las murallas a las mesas bohemias.",
    routeNote:
      "Seis lugares. Un paseo. Con tiempo de sobra para un café, un desvío o unas buenas vistas.",
    expectKicker: "Hecho para pasear, no para mirar la pantalla.",
    expectTitle: "Una ruta que puedes disfrutar de verdad tu primer día en Belgrado.",
    expectOneTitle: "Calles reales, no líneas rectas.",
    expectOneBody:
      "Cada trazado del mapa sigue aceras y pasajes por los que se puede caminar, con distancias honestas.",
    expectTwoTitle: "Escucha a tu manera.",
    expectTwoBody:
      "El piloto usa la voz del propio navegador, así que no hay descargas raras ni archivos de audio.",
    expectThreeTitle: "Pensado para la calle.",
    expectThreeBody:
      "Activa la ubicación cuando quieras, o sigue adelante con indicaciones escritas claras.",
    footerLine: "Historias de Belgrado, a tu ritmo.",

    back: "Atrás",
    setupKicker: "Stari Grad · ruta piloto",
    setupTitle: "Ajusta tu manera de caminar.",
    setupBody: "Un par de decisiones rápidas y la ciudad es tuya.",
    chooseLanguage: "Elige un idioma",
    languageNoteReady: "La narración y las indicaciones están traducidas por completo.",
    languageNotePending:
      "Este idioma todavía no está escrito: el paseo se queda en inglés por ahora.",
    chooseTheme: "Elige un tema",
    themeHistory: "Historia",
    themeHistoryBody: "Murallas, monumentos e historias entre medias.",
    chooseLength: "¿Cuánto tiempo tienes?",
    chooseDirection: "¿Desde dónde empiezas?",
    openTour: "Abrir la ruta piloto",

    counter: "Piloto",
    mapKicker: "Mapa interactivo",
    mapTitle: "Sigue el paseo",
    mapHint:
      "Toca una parada numerada para abrir su historia, o un punto tenue para añadir un desvío.",
    mapWholeRoute: "Ruta completa",
    mapThisStop: "Esta parada",
    mapExpand: "Ampliar mapa",
    mapCollapse: "Cerrar mapa",
    mapLegendRoute: "Tu ruta",
    mapLegendAlternative: "Alternativa",
    mapLegendDetour: "Desvío",
    mapLocationOn: "Tu ubicación aparece en turquesa.",
    mapLocationOff: "La ubicación es opcional: la ruta funciona igual sin ella.",

    yourRoute: "Tu ruta",
    routeName: "Paseo histórico por Stari Grad",
    routeSummary: "{distance} · {minutes} min andando",
    routeSummaryDetours: "{distance} · {minutes} min andando · +{detour} min de desvíos",
    stopWord: "Parada",

    narrationReady: "Listo para escuchar",
    narrationPlaying: "Narración en marcha",
    narrationPaused: "Narración en pausa",
    narrationSource: "Voz del navegador",
    playStory: "Reproducir historia",
    resumeStory: "Reanudar historia",
    pause: "Pausa",
    stopNarration: "Detener la narración",
    listenOrRead: "Escucha o lee mientras tanto.",
    narrationUnsupported:
      "La narración de audio no está disponible en este navegador. Puedes leer la historia abajo.",
    narrationFailed:
      "Tu navegador no ha podido iniciar la narración. Inténtalo otra vez o lee la historia.",
    narrationNoVoice:
      "Tu dispositivo no tiene instalada una voz en {language}, así que esta parada es solo texto. Todo lo escrito sigue traducido.",

    locationTitle: "Ubicación en directo, si quieres",
    locationIdle: "Activa la ubicación para ver cuándo estás cerca de cada parada.",
    locationLoading: "Buscando tu ubicación…",
    locationDenied:
      "Se ha denegado el permiso de ubicación. No pasa nada: usa las indicaciones escritas.",
    locationUnavailable:
      "La ubicación no está disponible en este dispositivo. La ruta funciona con las indicaciones.",
    locationArrived: "Estás en esta parada: dale al play cuando quieras.",
    locationDistance: "A {distance} de esta parada. Sigue las indicaciones.",
    useMyLocation: "Usar mi ubicación",
    checkingLocation: "Comprobando ubicación",

    walkNext: "Siguiente tramo",
    walkStat: "{minutes} min · {distance}",
    nextStop: "Siguiente parada: {title}",
    finishTour: "Terminar el piloto",
    tourComplete: "Ruta completada",
    tourCompleteBody:
      "Desde aquí vuelves fácilmente al centro o te pierdes tranquilamente por el barrio.",
    directionReverseNote:
      "Las indicaciones escritas se redactaron para el paseo que empieza en la fortaleza. En este sentido, sigue la línea del mapa: la distancia y el tiempo de arriba sí son correctos.",
    pathChoice: "Dos maneras de hacer este tramo",
    pathChosen: "Vas por aquí",
    detourTitle: "Merece un desvío",
    detourNone: "En este tramo no hay nada por lo que valga la pena salirse de la ruta.",
    detourAdd: "Añadir",
    detourAdded: "Añadido",
    detourMinutes: "+{minutes} min",
    walksKicker: "Belgrado, un paseo a la vez",
    walksTitle: "Elige un paseo.",
    walksBody: "El paseo por Stari Grad es gratis y lo seguirá siendo. Los barrios nuevos llegan con la suscripción.",
    walkStops: "{count} paradas",
    badgeFreeWalk: "Gratis",
    badgeSubscriberWalk: "Suscripción",
    lockedNote: "Incluido en la suscripción mensual. La compra se hace en la app de Android.",
    lockedNoteWeb: "Incluido en la suscripción mensual, que se vende a través de la app de Android.",
    allWalks: "Todos los paseos",
    openWalk: "Abrir este paseo",
    offerCode: "Código",
    offerHint: "Muestra esta pantalla en la caja.",
    walkEnglishOnly: "Este paseo solo está escrito en inglés por ahora.",
    voiceMissing: "Sin voz en este dispositivo",
    voiceAvailable: "Se puede escuchar",
    voiceHelpAndroid: "Para oír este idioma, instala su voz: Ajustes → Administración general → Texto a voz → tu motor → Instalar datos de voz.",
    voiceHelpIos: "Para oír este idioma, añade su voz: Ajustes → Accesibilidad → Contenido leído → Voces.",
    voiceHelpDesktop: "Tu navegador no tiene voz para este idioma. Los móviles suelen tenerla, o puedes leerlo.",
    narrationRecorded: "Voz grabada",
    chooseWalkHere: "Cinco paseos, uno gratis",
    subscribe: "Suscribirse",
    subscribePerMonth: "{price} / mes",
    subscribeAllWalks: "Desbloquea todos los paseos, en todos los idiomas.",
    subscribeThanks: "Gracias: todos los paseos están desbloqueados.",
    subscribeFailed: "La compra no se completó. No se ha cobrado nada.",
    subscribeCancelled: "Compra cancelada. No se ha cobrado nada.",
    subscribeUnavailable: "Por ahora solo se puede suscribir en la app de Android.",
    openFreeWalk: "Abrir el paseo gratuito",
    language: "Idioma",
    theme: "Tema",
    themeSystem: "Sistema",
    themeLight: "Claro",
    themeDark: "Oscuro",
  },
};
