import type { UiStrings } from "@/lib/i18n";

export const sr: UiStrings = {
  name: "Srpski",
  speechLang: "sr-RS",
  strings: {

    pilotTour: "Pilot tura",
    stariGrad: "Stari grad",
    heroKicker: "Beograd, u tvom uhu",
    heroTitle: "Grad je bolji kada ti uzvrati priču.",
    heroBody:
      "Razigrana šetnja kroz beogradsku staru varoš, napravljena za telefon. Izaberi jezik, prati stanice i pusti priču kada budeš spreman. Radi i kada nestane signal.",
    startWalk: "Počni šetnju",
    seeRoute: "Pogledaj rutu",
    badgeTime: "75–90 minuta",
    badgeFree: "Besplatno pilot izdanje",
    badgeBrowser: "Radi u pregledaču",
    todaysRoute: "Današnja ruta",
    routeHeadline: "Od bedema do boemskih stolova.",
    routeNote:
      "Šest mesta. Jedna šetnja. Dovoljno prostora za kafu, skretanje ili odličan pogled.",
    expectKicker: "Napravljeno za lutanje, ne za buljenje u ekran.",
    expectTitle: "Ruta u kojoj možeš stvarno da uživaš prvog dana u Beogradu.",
    expectOneTitle: "Prave ulice, ne prave linije.",
    expectOneBody:
      "Svaka putanja na mapi prati trotoare i prolaze kojima zaista možeš da prođeš, sa poštenim rastojanjima.",
    expectTwoTitle: "Slušaj kako ti odgovara.",
    expectTwoBody:
      "Pilot koristi ugrađeni govor tvog pregledača, pa nema nikakvih preuzimanja ni audio fajlova.",
    expectThreeTitle: "Napravljeno za ulicu.",
    expectThreeBody:
      "Uključi lokaciju kada poželiš, ili nastavi dalje uz jasna pisana uputstva.",
    footerLine: "Beogradske priče, tvojim tempom.",

    back: "Nazad",
    setupKicker: "Stari grad · pilot tura",
    setupTitle: "Podesi raspoloženje za šetnju.",
    setupBody: "Nekoliko brzih izbora, a onda je grad tvoj.",
    chooseLanguage: "Izaberi jezik",
    languageNoteReady: "Naracija i uputstva su u potpunosti prevedeni.",
    languageNotePending:
      "Ovaj jezik još nije napisan — šetnja za sada ostaje na engleskom.",
    chooseTheme: "Izaberi temu",
    themeHistory: "Istorija",
    themeHistoryBody: "Bedemi, gradski spomenici i priče između njih.",
    chooseLength: "Koliko vremena imaš?",
    chooseDirection: "Odakle krećeš?",
    openTour: "Otvori pilot turu",

    counter: "Pilot",
    mapKicker: "Interaktivna mapa",
    mapTitle: "Prati šetnju",
    mapHint:
      "Dodirni numerisanu stanicu da otvoriš njenu priču, ili bledu oznaku da dodaš skretanje.",
    mapWholeRoute: "Cela ruta",
    mapThisStop: "Ova stanica",
    mapExpand: "Uvećaj mapu",
    mapCollapse: "Zatvori mapu",
    mapLegendRoute: "Tvoja ruta",
    mapLegendAlternative: "Alternativa",
    mapLegendDetour: "Skretanje",
    mapLocationOn: "Tvoja lokacija je prikazana tirkizno.",
    mapLocationOff: "Lokacija je opciona — cela ruta radi i bez nje.",

    yourRoute: "Tvoja ruta",
    routeName: "Istorijska šetnja Starim gradom",
    routeSummary: "{distance} · {minutes} min hoda",
    routeSummaryDetours: "{distance} · {minutes} min hoda · +{detour} min skretanja",
    stopWord: "Stanica",

    narrationReady: "Spremno za slušanje",
    narrationPlaying: "Naracija ide",
    narrationPaused: "Naracija pauzirana",
    narrationSource: "Govor pregledača",
    playStory: "Pusti priču",
    resumeStory: "Nastavi priču",
    pause: "Pauza",
    stopNarration: "Zaustavi naraciju",
    listenOrRead: "Slušaj ili čitaj uz to.",
    narrationUnsupported:
      "Zvučna naracija nije dostupna u ovom pregledaču. Priču možeš pročitati ispod.",
    narrationFailed:
      "Tvoj pregledač nije mogao da pokrene naraciju. Pokušaj ponovo ili pročitaj priču.",
    narrationNoVoice:
      "Tvoj uređaj nema instaliran {language} glas, pa je ova stanica samo tekst. Sve napisano je i dalje prevedeno.",

    locationTitle: "Lokacija uživo, ako želiš",
    locationIdle: "Uključi lokaciju da vidiš kada si blizu svake stanice.",
    locationLoading: "Tražim tvoju lokaciju…",
    locationDenied:
      "Dozvola za lokaciju je odbijena. Nema veze — koristi pisana uputstva ispod.",
    locationUnavailable:
      "Lokacija nije dostupna na ovom uređaju. Ruta i dalje radi uz uputstva.",
    locationArrived: "Na ovoj si stanici — pusti priču kada budeš spreman.",
    locationDistance: "{distance} od ove stanice. Nastavi da pratiš uputstva.",
    useMyLocation: "Koristi moju lokaciju",
    checkingLocation: "Proveravam lokaciju",

    walkNext: "Sledeća deonica",
    walkStat: "{minutes} min · {distance}",
    nextStop: "Sledeća stanica: {title}",
    finishTour: "Završi pilot",
    tourComplete: "Tura završena",
    tourCompleteBody:
      "Odavde je lak povratak do centra ili opuštena šetnja kroz kraj.",
    directionReverseNote:
      "Pisana uputstva su napisana za šetnju koja kreće od tvrđave. U ovom smeru prati liniju na mapi — rastojanje i vreme iznad su tačni.",
    pathChoice: "Dva načina da pređeš ovu deonicu",
    pathChosen: "Ideš ovuda",
    detourTitle: "Vredi skrenuti",
    detourNone: "Na ovoj deonici nema ničega zbog čega bi vredelo sići s rute.",
    detourAdd: "Dodaj",
    detourAdded: "Dodato",
    detourMinutes: "+{minutes} min",
    walksKicker: "Beograd, jedna šetnja po jedna",
    walksTitle: "Izaberi šetnju.",
    walksBody: "Šetnja Starim gradom je besplatna i takva ostaje. Novi kvartovi idu uz pretplatu.",
    walkStops: "{count} stanica",
    badgeFreeWalk: "Besplatno",
    badgeSubscriberWalk: "Pretplata",
    lockedNote: "Deo mesečne pretplate. Kupovina je moguća u Android aplikaciji.",
    lockedNoteWeb: "Deo mesečne pretplate, koja se prodaje preko Android aplikacije.",
    allWalks: "Sve šetnje",
    openWalk: "Otvori ovu šetnju",
    offerCode: "Kod",
    offerHint: "Pokaži ovaj ekran na kasi.",
    walkEnglishOnly: "Ova šetnja je za sada napisana samo na engleskom.",
    voiceMissing: "Na ovom uređaju nema glasa",
    voiceAvailable: "Može se čitati naglas",
    voiceHelpAndroid: "Da bi ovaj jezik mogao da se čuje, instaliraj glas: Podešavanja → Opšte upravljanje → Tekst u govor → tvoj mehanizam → Instaliraj glasovne podatke.",
    voiceHelpIos: "Da bi ovaj jezik mogao da se čuje, dodaj glas: Podešavanja → Pristupačnost → Izgovoreni sadržaj → Glasovi.",
    voiceHelpDesktop: "Tvoj pregledač nema glas za ovaj jezik. Telefoni ga obično imaju — ili čitaj uz to.",
    narrationRecorded: "Snimljeni glas",
    chooseWalkHere: "Pet šetnji, jedna besplatna",
    subscribe: "Pretplati se",
    subscribePerMonth: "{price} / mesečno",
    subscribeAllWalks: "Otključava sve šetnje, na svim jezicima.",
    subscribeThanks: "Hvala — sve šetnje su otključane.",
    subscribeFailed: "Kupovina nije prošla. Ništa nije naplaćeno.",
    subscribeCancelled: "Kupovina je otkazana. Ništa nije naplaćeno.",
    subscribeUnavailable: "Pretplata je za sada moguća samo u Android aplikaciji.",
    openFreeWalk: "Otvori besplatnu šetnju",
    language: "Jezik",
    theme: "Tema",
    themeSystem: "Sistemska",
    themeLight: "Svetla",
    themeDark: "Tamna",
  },
};
