import type { UiStrings } from "@/lib/i18n";

export const tr: UiStrings = {
  name: "Türkçe",
  speechLang: "tr-TR",
  strings: {

    pilotTour: "Pilot tur",
    stariGrad: "Stari Grad",
    heroKicker: "Belgrad, kulağında",
    heroTitle: "Şehir konuşmaya başlayınca güzelleşiyor.",
    heroBody:
      "Belgrad’ın eski şehrinde, telefonunla yapılan keyifli bir yürüyüş. Dilini seç, durakları takip et, dinlemeye hazır olduğunda başlat. Şebeke çekmese de çalışmaya devam eder.",
    startWalk: "Yürüyüşe başla",
    seeRoute: "Rotayı gör",
    badgeTime: "75–90 dakika",
    badgeFree: "Ücretsiz pilot deneyim",
    badgeBrowser: "Tarayıcında çalışır",
    todaysRoute: "Bugünün rotası",
    routeHeadline: "Kale duvarlarından bohem masalara.",
    routeNote:
      "Altı yer. Bir yürüyüş. Bir kahveye, bir sapmaya ya da güzel bir manzaraya bolca yer var.",
    expectKicker: "Ekrana bakmak için değil, gezinmek için tasarlandı.",
    expectTitle: "Belgrad'daki ilk gününde gerçekten keyif alacağın bir rota.",
    expectOneTitle: "Düz çizgiler değil, gerçek sokaklar.",
    expectOneBody:
      "Haritadaki her yol, gerçekten yürüyebileceğin kaldırım ve geçitleri takip eder; mesafeler dürüsttür.",
    expectTwoTitle: "Kendi yönteminle dinle.",
    expectTwoBody:
      "Pilot sürüm tarayıcının kendi konuşma özelliğini kullanır; gizemli indirmeler ya da ses dosyaları yok.",
    expectThreeTitle: "Sokak için yapıldı.",
    expectThreeBody:
      "İstediğinde konumunu aç, ya da net yazılı tariflerle yoluna devam et.",
    footerLine: "Belgrad hikâyeleri, senin hızında.",

    back: "Geri",
    setupKicker: "Stari Grad · pilot tur",
    setupTitle: "Yürüyüş modunu ayarla.",
    setupBody: "Birkaç hızlı seçim, sonra şehir senin.",
    chooseLanguage: "Dil seç",
    languageNoteReady: "Anlatım ve tarifler tamamen çevrildi.",
    languageNotePending:
      "Bu dil henüz yazılmadı — yürüyüş şimdilik İngilizce kalıyor.",
    chooseTheme: "Tema seç",
    themeHistory: "Tarih",
    themeHistoryBody: "Kale duvarları, şehrin simgeleri ve aradaki hikâyeler.",
    chooseLength: "Ne kadar vaktin var?",
    chooseDirection: "Nereden başlıyorsun?",
    openTour: "Pilot turu aç",

    counter: "Pilot",
    mapKicker: "Etkileşimli harita",
    mapTitle: "Yürüyüşü takip et",
    mapHint:
      "Hikâyesini açmak için numaralı bir durağa, sapma eklemek için soluk bir işarete dokun.",
    mapWholeRoute: "Tüm rota",
    mapThisStop: "Bu durak",
    mapExpand: "Haritayı büyüt",
    mapCollapse: "Haritayı kapat",
    mapLegendRoute: "Rotan",
    mapLegendAlternative: "Alternatif",
    mapLegendDetour: "Sapma",
    mapLocationOn: "Konumun turkuaz renkte gösteriliyor.",
    mapLocationOff: "Konum isteğe bağlı — rota onsuz da tamamen çalışır.",

    yourRoute: "Rotan",
    routeName: "Stari Grad tarih yürüyüşü",
    routeSummary: "{distance} · {minutes} dk yürüyüş",
    routeSummaryDetours: "{distance} · {minutes} dk yürüyüş · +{detour} dk sapma",
    stopWord: "Durak",

    narrationReady: "Dinlemeye hazır",
    narrationPlaying: "Anlatım çalıyor",
    narrationPaused: "Anlatım duraklatıldı",
    narrationSource: "Tarayıcı sesi",
    playStory: "Hikâyeyi başlat",
    resumeStory: "Devam et",
    pause: "Duraklat",
    stopNarration: "Anlatımı durdur",
    listenOrRead: "Dinle ya da birlikte oku.",
    narrationUnsupported:
      "Bu tarayıcıda sesli anlatım yok. Hikâyeyi aşağıdan okuyabilirsin.",
    narrationFailed:
      "Tarayıcın bu anlatımı başlatamadı. Tekrar dene ya da hikâyeyi oku.",
    narrationNoVoice:
      "Cihazında {language} sesi yüklü değil, bu yüzden bu durak yalnızca metin. Yazılı olan her şey yine de çevrilmiş durumda.",

    locationTitle: "İstersen canlı konum",
    locationIdle: "Duraklara yaklaştığını görmek için konumu aç.",
    locationLoading: "Konumun aranıyor…",
    locationDenied:
      "Konum izni verilmedi. Sorun değil — aşağıdaki yazılı tarifleri kullan.",
    locationUnavailable:
      "Bu cihazda konum kullanılamıyor. Rota tariflerle yine çalışıyor.",
    locationArrived: "Bu duraktasın — hazır olduğunda başlat.",
    locationDistance: "Bu duraktan {distance} uzaktasın. Tarifleri takip etmeye devam et.",
    useMyLocation: "Konumumu kullan",
    checkingLocation: "Konum kontrol ediliyor",

    walkNext: "Sıradaki yürüyüş",
    walkStat: "{minutes} dk · {distance}",
    nextStop: "Sonraki durak: {title}",
    finishTour: "Pilotu bitir",
    tourComplete: "Tur tamamlandı",
    tourCompleteBody:
      "Buradan merkeze dönmek kolay bir yürüyüş, ya da mahallede keyifle dolaşabilirsin.",
    directionReverseNote:
      "Yazılı tarifler kaleden başlayan yürüyüş için yazıldı. Bu yönde giderken haritadaki çizgiyi takip et — yukarıdaki mesafe ve süre doğru.",
    pathChoice: "Bu bölümü yürümenin iki yolu",
    pathChosen: "Bu yoldan gidiyorsun",
    detourTitle: "Sapmaya değer",
    detourNone: "Bu bölümde rotadan ayrılmaya değecek bir şey yok.",
    detourAdd: "Ekle",
    detourAdded: "Eklendi",
    detourMinutes: "+{minutes} dk",
    walksKicker: "Belgrad, her seferinde bir yürüyüş",
    walksTitle: "Bir yürüyüş seç.",
    walksBody: "Stari Grad yürüyüşü ücretsiz ve öyle kalacak. Yeni mahalleler abonelikle geliyor.",
    walkStops: "{count} durak",
    badgeFreeWalk: "Ücretsiz",
    badgeSubscriberWalk: "Abonelik",
    lockedNote: "Aylık aboneliğe dahil. Satın alma Android uygulamasında yapılabiliyor.",
    lockedNoteWeb: "Aylık aboneliğe dahil; abonelik Android uygulaması üzerinden satılıyor.",
    allWalks: "Tüm yürüyüşler",
    openWalk: "Bu yürüyüşü aç",
    offerCode: "Kod",
    offerHint: "Kasada bu ekranı göster.",
    walkEnglishOnly: "Bu yürüyüş şimdilik yalnızca İngilizce yazıldı.",
    voiceMissing: "Bu cihazda ses yok",
    voiceAvailable: "Sesli okunabilir",
    voiceHelpAndroid: "Bu dili duymak için sesini yükle: Ayarlar → Genel yönetim → Metin okuma → motorun → Ses verilerini yükle.",
    voiceHelpIos: "Bu dili duymak için sesini ekle: Ayarlar → Erişilebilirlik → Sözlü İçerik → Sesler.",
    voiceHelpDesktop: "Tarayıcında bu dil için ses yok. Telefonlarda genelde var — ya da okuyarak takip et.",
    narrationRecorded: "Kayıtlı ses",
    chooseWalkHere: "Beş yürüyüş, biri ücretsiz",
    subscribe: "Abone ol",
    subscribePerMonth: "{price} / ay",
    subscribeAllWalks: "Bütün yürüyüşleri, bütün dillerde açar.",
    subscribeThanks: "Teşekkürler — bütün yürüyüşler açıldı.",
    subscribeFailed: "Satın alma tamamlanmadı. Hiçbir ücret alınmadı.",
    subscribeCancelled: "Satın alma iptal edildi. Hiçbir ücret alınmadı.",
    subscribeUnavailable: "Abonelik şimdilik yalnızca Android uygulamasında alınabiliyor.",
    openFreeWalk: "Ücretsiz yürüyüşü aç",
    language: "Dil",
    theme: "Tema",
    themeSystem: "Sistem",
    themeLight: "Açık",
    themeDark: "Koyu",
  },
};
