// GENERATED by scripts/make_audio.py — do not edit by hand.
//
// Lists the pre-recorded narration that shipped with this build, as
// "<tourId>/<stopId>" per language. The player consults this before
// reaching for the device's own speech engine, and falls back to it
// for anything not listed here.

export const audioManifest: Record<string, string[]> = {
  tr: [
    "vracar/cvetni",
    "vracar/slavija",
    "vracar/stmark",
    "vracar/temple",
    "vracar/tesla",
  ],
};
